# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Arty/MicroBlaze/MicroBlaze.cache/wt [current_project]
set_property parent.project_path C:/Arty/MicroBlaze/MicroBlaze.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty:part0:1.1 [current_project]
set_property ip_output_repo c:/Arty/MicroBlaze/MicroBlaze.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/hdl/system_wrapper.v
add_files C:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_clk_wiz_0_1/system_clk_wiz_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_clk_wiz_0_1/system_clk_wiz_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_clk_wiz_0_1/system_clk_wiz_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_mig_7series_0_1/system_mig_7series_0_1/user_design/constraints/system_mig_7series_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_mig_7series_0_1/system_mig_7series_0_1/user_design/constraints/system_mig_7series_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_mig_7series_0_1/system_mig_7series_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_microblaze_0_1/system_microblaze_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_microblaze_0_1/system_microblaze_0_1_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_microblaze_0_1/system_microblaze_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_mdm_1_1/system_mdm_1_1.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_mdm_1_1/system_mdm_1_1_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_rst_mig_7series_0_83M_1/system_rst_mig_7series_0_83M_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_rst_mig_7series_0_83M_1/system_rst_mig_7series_0_83M_1.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_rst_mig_7series_0_83M_1/system_rst_mig_7series_0_83M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_axi_uartlite_0_1/system_axi_uartlite_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_axi_uartlite_0_1/system_axi_uartlite_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_axi_uartlite_0_1/system_axi_uartlite_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_39/bd_8422_s00a2s_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_48/bd_8422_s01a2s_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_51/bd_8422_m00s2a_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_52/bd_8422_m00arn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_53/bd_8422_m00rn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_54/bd_8422_m00awn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_55/bd_8422_m00wn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_56/bd_8422_m00bn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_49/bd_8422_sarn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_50/bd_8422_srn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_40/bd_8422_sarn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_41/bd_8422_srn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_42/bd_8422_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_43/bd_8422_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_44/bd_8422_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_31/bd_8422_arsw_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_32/bd_8422_rsw_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_33/bd_8422_awsw_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_34/bd_8422_wsw_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_35/bd_8422_bsw_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_30/bd_8422_psr_aclk_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_30/bd_8422_psr_aclk_1.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_axi_smc_1/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_dlmb_v10_1/system_dlmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_dlmb_v10_1/system_dlmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_ilmb_v10_1/system_ilmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_ilmb_v10_1/system_ilmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_dlmb_bram_if_cntlr_1/system_dlmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_ilmb_bram_if_cntlr_1/system_ilmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/ip/system_lmb_bram_1/system_lmb_bram_1_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/system_ooc.xdc]
set_property is_locked true [get_files C:/Arty/MicroBlaze/MicroBlaze.srcs/sources_1/bd/system/system.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top system_wrapper -part xc7a35ticsg324-1L


write_checkpoint -force -noxdef system_wrapper.dcp

catch { report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb }
